# Generated by Django 4.2.5 on 2023-09-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.CharField(choices=[('HOT', 'HOT FIX'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20),
        ),
    ]
